
server:
  port: 8080
spring:
  application:
    name: config-test
  cloud:
   config:
    server:
      git:
        uri: https://github.com/nigshao/nclound.git #配置文件在github上的地址
         #clone-on-start: true #启动时就clone仓库到本地，默认是在配置被首次请求时，config server才会clone git仓库
               #native:
                #search-locations: classpath:/config #若配置中心在本地，本地的地址