spring:
  profiles:
    active: dev
server:
  port: 3000
eureka:
  server:
    #Eureka还有自我保护机制，如果在15分钟内超过85%节点都没有正常心跳，那么eureka就认为客户端与注册中心出现了网络故障，此时会出现以下情况
    enable-self-preservation: false #关闭自我保护机制,打开了注册机制  true关闭  false不关闭
    eviction-interval-timer-in-ms: 4000 #设置清理间隔（单位：毫秒 默认是60*1000，将死掉的服务剔除）
  instance: eureka3000.com
  client:
    registerWithEureka: true #不把自己作为一个客户端注册到自己身上  集群的话就打开
    fetchRegistry: true #不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用自己注
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #集群搭建
      defaultZone: http://eureka3001.com:3001/eureka,http://eureka3002.com:3002/eureka